### ISSUE TITLE
PyLinac tg51 class is not fully SI compatible

### ISSUE THREAD

**Issue by jmartens** [jrkerns/pylinac#110]
Being from Europe I was a bit surprised my results were off when I entered my values. I traced it down to the `p_tp` class and found the documentation stating 
It seems `tg51` class is calculating pressure based on mmHg, where the [documentation referencing the TG-51 formulas](https://pylinac.readthedocs.io/en/latest/tg51_docs.html) seem to use a reference pressure in kPa, judging from it's value. 

```
    press : float
        The pressure in mmHg.
```

I think this should be aligned with each other. 

I would prefer the SI units (and therefore pressure in (k)Pa, but I could imagine, for backwards compatibility reason, you'd prefer the documentation to be changed and use the mmHg reference value (760 mmHg) in the equation in the documentation.

**Comment by jrkerns** [comment]
Wow, thanks for the catch! Yes, pylinac is based on mmHg. I will correct the documentation to reflect this; you are right, I will stick with mmHg for the time being. I am also working on adding warnings for any TG-51 parameter that is far out of tolerance (e.g. if kPa were used and makes the c_tp value far off from 1.0). Appreciated!
