### ISSUE TITLE
Refactor PDF module

### ISSUE THREAD

**Issue by jrkerns** [jrkerns/pylinac#132]

**Comment by keithoffer** [comment]
I was looking at doing some work to improve the PDF reports (in particular fix things like long file names squishing the images), but noticed that you've set this issue up. What do you plan on refactoring? Are you planning to modify the file reports being generated as part of the refactoring process?

**Comment by jrkerns** [comment]
Hi Keith, sorry for the super late reply. 

I needed to refactor it to modularize the functions and so forth. Each module had all kinds of spaghetti code using pdf functions. The long file names is indeed an issue I've seen. I was thinking about possibly just using the last ~30 characters or so of the full file name. That way it wouldn't overflow.
