### ISSUE TITLE
Potential to use ScriptedForms to create online demos?

### ISSUE THREAD

**Issue by SimonBiggs** [jrkerns/pylinac#135]
Hi @jrkerns,

I'm not sure if you would be keen, but I have been using PyLinac to create a demos of using ScriptedForms. For example:

https://mybinder.org/v2/gh/SimonBiggs/scriptedforms-examples/master?urlpath=scriptedforms/use/pylinac.form.md

If you're interested I would be happy to make some more if you wanted to use them for pylinac docs.

Cheers,
Simon

**Comment by jrkerns** [comment]
Really cool! I've been meaning to explore the scriptedforms repo; clearly it's gaining traction. I think something like this would be great for a small clinic that wants to have some type of GUI for pylinac that's not 80's tkinter style =)

**Comment by SimonBiggs** [comment]
Thanks James :).

Hopefully also the underlying code that updates/changes the GUI is more
easily parsed and edited by non-programmers. That's the plan anyway.

Here's the file that creates that form:
https://raw.githubusercontent.com/SimonBiggs/scriptedforms-examples/master/pylinac.form.md
