### ISSUE TITLE
Error when running FlatSym demo

### ISSUE THREAD

**Issue by bobred** [jrkerns/pylinac#137]
I am running Python 3.6.1 (Anaconda Windows) and pylinac 2.1.0.1 and dependencies are as stated in the documentation. When running the demo

```
from pylinac import FlatSym
FlatSym.run_demo()
```
I get the error

```
Traceback (most recent call last):
  File "D:/Test1.py", line 10, in <module>
    from pylinac import FlatSym
ImportError: cannot import name 'FlatSym'

Process finished with exit code 1
```

Any ideas please?

**Comment by jrkerns** [comment]
This is called BeamImage in v2.1 and under. It was rewritten in v2.2 and is now called FlatSym. Let me know if you have any issues with that solution. Thanks
