### ISSUE TITLE
AttributeError: module 'pylinac.core.pdf' has no attribute 'create_pylinac_page_template'

### ISSUE THREAD

**Issue by tianxingqian** [jrkerns/pylinac#153]
1. Go to 'pylinac.gui()'
2. Click on 'Machine Logs -> Select log file -> click Analyze button '
3. In IDE console, show the error :
   `File "F:\study\pylinac\pylinac\log_analyzer.py", line 2116, in publish_pdf
    canvas = pdf.create_pylinac_page_template(filename, analysis_title="Trajectory Log Analysis", 
           unit=unit,
       AttributeError: module 'pylinac.core.pdf' has no attribute 'create_pylinac_page_template'`

**Comment by jrkerns** [comment]
Fix on the way
