### ISSUE TITLE
Catphan analysis : fantom roll

### ISSUE THREAD

**Issue by jlley** [jrkerns/pylinac#158]
**Describe the bug**

The function find_catphan_roll() in ct.py doesn't work properly everytime. When we analyze the Catphan 504 images, the roll angle is sometimes around 13 degrees even if the fantom is well positionned. 
We found that it come from the detection of the air insert at 12h. If the value from the is_right_area() is out of the range for the threshold, the program takes the closest insert instead of the air insert.

**To Reproduce**

**Expected behavior**

In the function : def find_phantom_roll(self): and then def is_right_area(region):
Could you change the inferior limit from 1.5 to 2 please ?
    original code:   return thresh * 1.5 > region.filled_area > thresh / 1.5 
    update:  return thresh * 2 > region.filled_area > thresh / 1.5 

**Screenshots**

**Additional context**

**Comment by jrkerns** [comment]
Looks like this would work. Need to run it on my larger private dataset though. #159

**Comment by jrkerns** [comment]
Will be in v2.2.3
