### ISSUE TITLE
Dynalog fluence error for VMAT treatments

### ISSUE THREAD

**Issue by jrkerns** [jrkerns/pylinac#169]
VMAT Dynalogs replace the dose fraction (i.e. the 0-25000) to the gantry axis value. Dose information should be normalized to the gantry movement.

**Comment by Centrus007** [comment]
Hi James,

I'm no sure if you're already aware of this, but I thought I'd mention the following regarding this issue:

VMAT Dynalogs replace the dose fraction with gantry angle *by default*, **but the user can change this by editing the MLC controller startup script.** Specifically, the user can remove '#' preceding the _diagUseRapidArcDynalogFormat_ command.

I believe your original fluence calculations were fine for any Dynalogs for which the above process had been followed. We certainly noticed no issue, and we went to considerable effort validating your fluence maps.

I wonder whether it is better to just keep your original implementation, but include a recommendation for the user to perform the above process in the pylinac docs. Up to you, of course. :)

For confirmation, see page 41 of Varian's [DynaLog File Viewer 8.1 Reference Guide.pdf](https://github.com/jrkerns/pylinac/files/3052738/DynaLog.File.Viewer.8.1.Reference.Guide.pdf)

**Comment by jrkerns** [comment]
Hi Matt, 
  Thanks for reporting this. I had overlooked that tidbit! All the VMAT dynalogs I have did not take advantage of that fact. 

I believe that if this change is enabled, i.e. it's back to using the relative 25000 dose index, then it should be fine (crosses fingers). See [here](https://github.com/jrkerns/pylinac/blob/master/pylinac/log_analyzer.py#L1646-L1654) where if the last index is 25000 no changes are made. 

If you provide a log like you described I would be happy to take a look at it.

**Comment by Centrus007** [comment]
No worries! Glad to see both cases are handled anyway - I missed that.

If you'd like to take a look, here is [a zip](https://github.com/jrkerns/pylinac/files/3056609/RapidArc_dynalogs_with_dose_fraction.zip) containing a set of dlogs of a 2-arc VMAT delivery with dose fraction reporting enabled.
