### ISSUE TITLE
Bakai Formula

### ISSUE THREAD

**Issue by bozhikovstanislav** [jrkerns/pylinac#183]
**Describe the bug**

        # equation: (measurement - reference) / sqrt ( doseTA^2 + distTA^2 * image_gradient^2 )
        subtracted_img = np.abs(comp_img - ref_img)
        denominator = np.sqrt((doseTA / 100.0 ** 2) + ((distTA_pixels ** 2) * (grad_img ** 2)))
        gamma_map = subtracted_img / denominator

Here the denominator say doseTA/100.0**2 - This is not true --- it must be (doseTA/100.0)**2 
as it is in the formula

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jrkerns** [comment]
This gives the same result in Python:
>>>1/100.0**2
0.0001
>>>(1/100)**2
0.0001

**Comment by bozhikovstanislav** [comment]
I am doing resurch on Gamma with a tests and
I do not like the results
I want to overide dostTA - because I want to use it .

**Comment by jrkerns** [comment]
I see now, yes for a value over 1 this is giving an incorrect value. The default is 1, so the default results should not change. Thanks for reporting
