### ISSUE TITLE
In Leeds TOR Phantom analysis, can we get data return from leeds.analyze function to plot analyzed image in custom developed UI?

### ISSUE THREAD

**Issue by sanjayrathod88** [jrkerns/pylinac#188]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The 'analyze' function should return data in the form of an array or list of object.

**Comment by jrkerns** [comment]
Analysis data is assigned to the instance. See https://pylinac.readthedocs.io/en/latest/planar_imaging.html#pylinac.planar_imaging.LeedsTOR.lc_rois and https://pylinac.readthedocs.io/en/latest/planar_imaging.html#pylinac.planar_imaging.LeedsTOR.hc_rois for attrs you can pull from.
