### ISSUE TITLE
Vertical and horizontal profiles swapped on FlatSym plot

### ISSUE THREAD

**Issue by alanphys** [jrkerns/pylinac#192]
**Describe the bug**
The vertical and horizontal profiles appear to be swapped on the plotted image, i.e the horizontal profile appears at the vertical profile offset and vice versa.

**To Reproduce**
In python console
`from pylinac import FlatSym`
`fs = FlatSym.from_demo_image()`
`fs.analyze("varian", "varian", 0.7, 0.2)`
`fs.plot()
`

**Expected behavior**
The vertical and horizontal profiles are not where I expect them to be.

**Screenshots**
See attached images. 
Figure_1.png is uncorrected behaviour
Figure_2.png is if I swap the "horizontal" and "vertical" dictionary labels in lines 312 and 313 of FlatSym.py
![Figure_1](https://user-images.githubusercontent.com/34305581/64173439-95126c80-ce57-11e9-9c9e-39512e3c848b.png)
![Figure_2](https://user-images.githubusercontent.com/34305581/64173447-99d72080-ce57-11e9-9c80-a523e440ab5e.png)

**Additional context**
I'll add a pull request if this is indeed the case.

Regards
Alan

**Comment by jrkerns** [comment]
Fixed in #193
