### ISSUE TITLE
Creating a pdf report of a picket fence analysis with a machine log file causes a traceback

### ISSUE THREAD

**Issue by keithoffer** [jrkerns/pylinac#199]
**Describe the bug**
If you call publish_pdf() on a PicketFence instance that was passed a trajectory log, you get a traceback rather than generating a pdf. Tested using version 2.2.7 from pypi (note that the package reports as 2.2.6 though).

**To Reproduce**
1. Initialise a PicketFence instance passing a machine log path
2. Call analyze()
3. Call publish_pdf()

Example code using PF.dcm and PF_log.bin from the tests_basic/test_files/Picket Fence/ folder in the repo:
```python
from pylinac import PicketFence

# Works
pf = PicketFence(filename='PF.dcm')
pf.analyze()
pf.publish_pdf('pf.pdf')

# Errors
pf = PicketFence(filename='PF.dcm',log='PF_log.bin')
pf.analyze()
pf.publish_pdf('pf_log.pdf')
```

Running the above code creates the following traceback:

Traceback (most recent call last):
  File "C:/Users/KeithOffer/PycharmProjects/pylinac_latest/log_report.py", line 11, in <module>
    pf.publish_pdf('pf_log.pdf')
  File "C:\Users\KeithOffer\PycharmProjects\pylinac_latest\venv\lib\site-packages\pylinac\picketfence.py", line 438, in publish_pdf
    f'Magnification factor (SID/SAD): {self.image.metadata.RTImageSID/self.image.metadata.RadiationMachineSAD:2.2f}',
AttributeError: 'ArrayImage' object has no attribute 'metadata'

**Expected behavior**
I would expect pdf reports to be able to be generated for picket fence analysis that were done with a machine log

**Additional context**
I tried to trace this error back to figure out why it was happening. It looks like at [this line in the _load_log function](https://github.com/jrkerns/pylinac/blob/5702bb0b67acb8216ec2cf5ea78dbb5e20fa3069/pylinac/picketfence.py#L214) the self.image attribute changes from a pylinac.picketfence.PFDicomImage to a pylinac.core.image.ArrayImage which dosen't have a 'metadata' attribute.

**Comment by jrkerns** [comment]
Yeah, it looks like the image may be converted from a DICOM image to an array image, which doesn't carry over the DICOM metadata.
