### ISSUE TITLE
Las Vegas

### ISSUE THREAD

**Issue by Zarita78** [jrkerns/pylinac#201]
Hi there,

I found this when trying to analyse a Las Vegas image. It seems that the routine is not able to place the ROIs correctly on the image. I attach the pdf obtained. 
[Las Vegas_20190721_D.pdf](https://github.com/jrkerns/pylinac/files/3606272/Las.Vegas_20190721_D.pdf)

Thanks very much.

**Comment by jrkerns** [comment]
Sadly, the planar imaging module has been more trouble than it's worth. Pylinac has always tried to subscribe to the idea that [the user shouldn't have to add extra information](https://pylinac.readthedocs.io/en/latest/overview.html#philosophy
) (like the angle). However, given the inability to correctly analyze these images on a non-negligble number of images I will be adding additional parameters to the analyze methods of the planar imaging classes in v2.8 to manually override the angle.

**Comment by Zarita78** [comment]
I understand but I don't think it's a big issue for Las Vegas phantom, as it's provided with a sticker on it showing how to position it on the couch. Therefore, the patterns would be always on the same position unless the physicist/technician is not placing the phantom in the right position. But I clearly see that it might an issue for Leeds TOR18FG. Thanks a lot and waiting for the next version then.

**Comment by jrkerns** [comment]
Yeah it'd be nice to have people do things the way they're supposed to. Here's a quick plot of LV images in my repo of images where each row is a separate clinic's images (yes I know there's a few that aren't; it was just a quick script for this purpose). As with most other phantoms, each clinic is consistent within itself, but can vary between clinics. 

![LV_acquisitions](https://user-images.githubusercontent.com/4803336/64911322-9c523980-d6e5-11e9-8b14-e5a39cf2c444.png)

**Comment by Zarita78** [comment]
Ok, I get you now :).
I'm a physicist and as you well say on your website... I'm only know how to program on Matlab... yet. Over the years, I have been using different methods to corroborate the results of my routines. Lately, I was using pylinac to do so... Always with really good agreement but for FlatSym... I've checked a good few times my routines and I read your code, I'm capable to follow to some extend...I'm not able to reproduce your results and going crazy! So I'd like to ask a favour, do you mind sharing the points of the 80% field profiles (vertical or horizontal, or both) you get before applying the formula for a Varian system? If it is a lot to ask, I understand. Many thanks in advance.

**Comment by jrkerns** [comment]
[This](https://github.com/jrkerns/pylinac/blob/master/pylinac/core/profile.py#L444-L463) is probably the function you're interested in. 

You can also play around more directly by doing something like this:
`from pylinac.core import profile, image`
`img = image.load(...)`
`prof = profile.SingleProfile(img[400, :] # change as needed to position of interest`
`(left_idx, right_idx) = prof.field_edges()`

**Comment by Zarita78** [comment]
Thanks very much. I will try that.
