### ISSUE TITLE
0 flatness interpreted as integer

### ISSUE THREAD

**Issue by alanphys** [jrkerns/pylinac#264]
**Describe the bug**
Perfectly flat images cause a traceback in the results() function because python is trying to display an integer as a float. Related to this is that the results in the "elekta" method are not being shown with sufficient precision or are shown in exponential form as below:

Flatness method: Elekta
Vertical flatness: 1e+02%
Horizontal flatness: 1e+02%
Symmetry method: Elekta
Vertical symmetry: 1e+02%
Horizontal symmetry: 1e+02%

**To Reproduce**
`from pylinac import FlatSym`
`fs = FlatSym('Test.dcm')`
`fs.analyze('varian', 'varian')`
`print(fs.results())`

or

`from pylinac import FlatSym`
`fs = FlatSym('Test.dcm')`
`fs.analyze('elekta', 'elekta')`
`print(fs.results())`

[Test.zip](https://github.com/jrkerns/pylinac/files/3873215/Test.zip)

**Expected behavior**
The results should be printed

**Workaround**
Add the f specifier to the precision format specifier. I will add a pull request for this.

**Additional context**
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/alanphys/Programs/pylinac/pylinac/flatsym.py", line 181, in results
    f"Vertical symmetry: {self.symmetry['vertical']['value']:3.3}%",
ValueError: Precision not allowed in integer format specifier

**Comment by jrkerns** [comment]
Good stuff, thanks
