### ISSUE TITLE
VMAT module passing criteria error

### ISSUE THREAD

**Issue by brjdenis** [jrkerns/pylinac#266]
Hi!

The VMAT module does not properly detect failed segments if the r_dev is negative. Line 423, I think, is the problem because no absolute value is used:

`return self.r_dev < self._tolerance * 100`

If you set the tolerance at 1 % and if r_dev for a particular segment is, say, -1.1 %, the segment will still have a passing status.

Best regards,
Denis

**Comment by jrkerns** [comment]
Verified. Good catch.
