### ISSUE TITLE
AttributeError: 'MTF' object has no attribute 'relative_resolution_at' (V2.3.0)

### ISSUE THREAD

**Issue by AlainSottiaux** [jrkerns/pylinac#282]
Hello James,

I just upgrade to V2.3.0 (from 2.2.6)
Catphan analysis (catphan504, from zip)
When trying to geneate pdf for results, I got:
File "(...)\lib\site-packages\pylinac\ct.py", line 1182, in publish_pdf
f'MTF 80% (lp/mm): {self.ctp528.mtf.relative_resolution_at(80):2.2f}',
AttributeError: 'MTF' object has no attribute 'relative_resolution_at'

same if I call results() instead of publish_pdf

when I try to change core\mtf.py line 43 from
    `def relative_resolution(self, x=50):`
to
    `def relative_resolution_at(self, x=50):`
it runs without error

Alain

**Comment by jrkerns** [comment]
Yup, fixed in #281. Will release a 2.3.1 today.
