### ISSUE TITLE
Catphan HU linearity plot: only absolute values

### ISSUE THREAD

**Issue by AlainSottiaux** [jrkerns/pylinac#290]
Catphan504, V2.3.1
HU Linearity test
On the plot, all values are positive, even if the measured HU is lower than the nominal value.

As far as I understand, the "value_diff" is plotted.
bu the value diff is absolute value
`    @property
    def value_diff(self):
        """The difference in HU between measured and nominal."""
        return abs(self.pixel_value - self.nominal_val)`

This is of course much easier for the pass/nopass test to have absolute value somewhere, but we expect the signed value on the plot.

**Comment by jrkerns** [comment]
Fair point
