### ISSUE TITLE
issues with Picket fence module 

### ISSUE THREAD

**Issue by maan8005** [jrkerns/pylinac#300]
**Describe the bug**
I have acquired several picket fence fields on TrueBeam with standerd MLC. Some are with known errors then analysed them using pylinac and noticed the following: 
- The module seems to underestimate the error by a factor of ~2 (i.e. leaves with known 1 mm errors are calculated as ~0.4-0.5 mm and leaves with 0.5 mm errors are calculated as 0.2-0.25 mm).
- If the A and B leaf-pair have same error magnitude (e.g. if A35 and B35 are 1 mm short) then pylinac report 0 error instead of 2 mm (or 1 mm in leaf A and 1 mm in leaf B) as the error is calculated (I think) by subtracting the centre of the leaf pair profile from the centre of the picket.
- The leaf numbering depends on the field size (e.g. if the error in leaf 30. For 20 cm field, pylinac reports leaf 20, for 30 cm field, pylinac reports 25, etc.)
- The leaf numbering is inverted (i.e. if the error in leaf-pair 5, pylinac report 55).
- For 40 cm field pylinac was not able to calculate the error in the first and last leave (even in the demo file). 
- (Minor issue) if the collimator is 0 deg, pylinac displays the image correctly, while, if the collimator is 90 deg, the image looks upside down.

Thank you
Maan Najem

**Comment by jrkerns** [comment]
Hi Maan, 
     Many of these issues are common to picket-fence analysis programs (e.g. Doselab). I've been playing around with a rework that looks at each leaf separately, but most people just need something that shows if a leaf is drifting or off and thus I haven't prioritized it. Also, it's free =). Pylinac can't correctly find or analyze leaves at the absolute edge of the field due to the algorithm assumptions that each leaf needs both edges to look "between". I'll have a look at the display issues, thanks.
