### ISSUE TITLE
CatPhan Find Origin Slice

### ISSUE THREAD

**Issue by 4Dct** [jrkerns/pylinac#312]
**Describe the bug**
Calling a set of CATPHAN503 images result in the failure to find the origin slice
"ValueError: No slices were found that resembled the HU linearity module"

**To Reproduce**
from pylinac import CatPhan503
cbct_folder = "mypath+file"
mycbct = CatPhan503(cbct_folder)
mycbct.analyze()

**Expected behavior**
the images are noisy (streak artifact) but the CTP404 module is visible (see attachment) and should show a circle profile contains both low (<800) and high (>800) HU values

**Screenshots**
CTP404 module slice
![Capture1](https://user-images.githubusercontent.com/71712442/93895941-4052c580-fce8-11ea-838b-a3e796fd5146.PNG)

thanks for your help, and pylinac which is great

**Comment by crcrewso** [comment]
There are quite a few issues with this image that would prevent the pylinac module from detecting it. The high  noise to contrast ratio would mess with the hu's and I can't even see the wires used for slice width. Do any of your other tools detect this as a ctp404 slice?

**Comment by 4Dct** [comment]
Thanks for that, I have commercial software where the ctp404 slice can be manually selected.

Can the find origin slice be easily set manually. For the majority of the datasets I have, the keyslice can be found with pylinac.

**Comment by crcrewso** [comment]
Not at present, there's a lot of autodetection going on that tries to make it unnecessary. That panel is either in pretty bad shape or you're underdosing for the scan mode. I would say that such analysis is far enough from standard to require manual analysis with your existing solution.
