### ISSUE TITLE
Catphan CTP 515 module maybe needs a subroutine to analyse the ROIs for CatPhan 600model?

### ISSUE THREAD

**Issue by tpeddles** [jrkerns/pylinac#317]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/72807231/95870651-a5885c80-0d64-11eb-8ec5-eb06c46cfd41.png)

The Pylinac analysis for low contrast is done with ROIs located in the top right quadrant of the Catphan.  The Catphan 600 is physically rotated 180 degrees (as shown in the diagram from the Catphan600 user manual), which puts the 1.0% supra-slice contrast targets in the lower left hand quadrant.  This means that the Pylinac analysis will not see any contrast targets for Catphan 600 models.

**Describe the solution you'd like**
Please would you consider putting in a subroutine for CatPhan 600 that places the ROIs in the lower half of the Catphan?  Thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by kkkkwan** [comment]
I am adding support for Catphan 500, and they hv the same CTP515 rotation. Plz wait
