### ISSUE TITLE
QC3 Documentation 

### ISSUE THREAD

**Issue by a-blackmore** [jrkerns/pylinac#322]
Planar Imaging - QC3 Docs area states:

Allowances

The images can be acquired at any SID.
**The phantom can be at any distance.**

Warning

Analysis can fail or give unreliable results if any Restriction is violated.

The phantom must not be touching any image edges.
The phantom should have the "1" pointing toward the gantry stand.
**The phantom should be at 100cm or 140cm**

Those two statements appear to be contradicting?

**Comment by randlet** [comment]
Hi Andy,

"The phantom should be at 100cm or 140cm" was added recently for a bug fix: https://github.com/jrkerns/pylinac/commit/ab3a9130ed292c4f3a018c8f34216219dd63b0a5

So "The phantom can be at any distance" is now in error I think.  You could fix this and create a pull request for this by editing the file online here: https://github.com/jrkerns/pylinac/blob/master/docs/source/planar_imaging.rst and removing the offending line.
