### ISSUE TITLE
Halcyon MLC And Pylinac

### ISSUE THREAD

**Issue by Zarita78** [jrkerns/pylinac#329]
Hi there,

I'd like to know if the picket fence and VMAT routines developed in Pylinac are good to use for Halcyon MLC. 

Thanks very much, 

Kind regards,

Zahara.

**Comment by alanphys** [comment]
Very much so, reply from a colleague that uses Halcyon below:

"Yes I do this each month. My results are quite good (the four common static gantry angles, and then RapidArc too)."

Regards
Alan
