### ISSUE TITLE
Converting Trajectory logs to CSV with R

### ISSUE THREAD

**Issue by cl49** [jrkerns/pylinac#330]
Converting Trajectory logs to CSV is made possible with pylinac with "log.to_csv()" function. 
Has anyone been aware of the same function with the R language?
If not, how can I know the content of the log.to_csv() function in order to program it in R?

Many thanks in advance,

Christof

**Comment by randlet** [comment]
@cl49 I don't know about R (it's not nearly as widely used in MedPhys as Python, so I suspect not) but the code for the Trajectory Log functionality, including `to_csv` is here: https://github.com/jrkerns/pylinac/blob/master/pylinac/log_analyzer.py
