### ISSUE TITLE
WLT ROI manipulation (trick/Tipp)

### ISSUE THREAD

**Issue by Kiragroh** [jrkerns/pylinac#366]
Hi,

can you please help me with a specific problem.

The left outside Panel of our Imager is defect (white column in test Images). Not a big problem for PortalDosimetry because it is not in center and can be mostly countered with calibration but WLT failed because pylinac things that the BB has to be in the column.

Is there a easy way to define/force a ROI in the center of a image? Or would you try to implemented code to ignore over exposured regions for automatic ROI finding?

thank you

**Comment by jrkerns** [comment]
I will be adding extra checks to the WL module to verify the BB is near the center of the image in the next version. For the time being, I would crop the images in an external program if possible.

**Comment by Kiragroh** [comment]
Thanks that you will work on that. Maybe this WLT-Images (with defect Panel region) will help with testing. Kind regards

https://ukede-my.sharepoint.com/:f:/g/personal/m_grohmann_uke_de/EjO65um6WDtKgH_YYXzBYnYBiPebHA9ZZTvza-6lQqHfGg?e=ZgH260
