### ISSUE TITLE
Add Support for SI QCkV-1 Phantom

### ISSUE THREAD

**Issue by randlet** [jrkerns/pylinac#379]
The QC-kV-1 is a phantom for measuring MTF, contrast, noise from linac kV imaging systems and it would be nice to have support in Pylinac for it.  I will upload a sample image once I have confirmed I can share it.

![image](https://user-images.githubusercontent.com/78128/115940413-7e2aee80-a46f-11eb-9b13-5ada945204a7.png)

**Comment by jrkerns** [comment]
Sample images can go here for anyone interested: https://www.dropbox.com/request/YKRu4AmuPsXu55uQq761 One sample image is here: https://groups.google.com/g/pylinac/c/qIeKrOIWp0s

**Comment by jrkerns** [comment]
Work is in this branch: https://github.com/jrkerns/pylinac/tree/Add_qckv1
