### ISSUE TITLE
Add support for SI FC-2 Rad-Light Phantom

### ISSUE THREAD

**Issue by randlet** [jrkerns/pylinac#380]
The FC-2 is a phantom made by SI for doing EPID based Rad-Light testing. 

![image](https://user-images.githubusercontent.com/78128/115940553-f72a4600-a46f-11eb-84c2-bf14a3cb2f10.png)

Maybe better to do a generalized rad-light EPID based test instead of FC-2 specific?

I will upload example image once I have confirmation I can share.

**Comment by jrkerns** [comment]
Added in v3.1.
