### ISSUE TITLE
How to read tiff image with PicketFence

### ISSUE THREAD

**Issue by chg0901** [jrkerns/pylinac#387]
As the title shows

**Comment by randlet** [comment]
Hi @chg0901 ,

In theory I think the PF module can handle TIFF images, so in order to make this a more useful issue it would be helpful if you could describe what you've tried, what error you got and to provide a sample image so it's easy to debug what the problem is.

**Comment by jrkerns** [comment]
pylinac does not yet support non-DICOM images for picketfence.
