### ISSUE TITLE
Incorrect Documentation of CBCT Analysis?

### ISSUE THREAD

**Issue by t-milan** [jrkerns/pylinac#398]
In the [documentation ](https://pylinac.readthedocs.io/en/stable/cbct_docs.html#analysis) of the CatPhan module, the following is stated in regards to HU linearity: 
"The mean pixel value of the ROI is the stated HU value."

However, in `ROI.py`, it seems to take the median: 
```py
@cached_property
def pixel_value(self) -> float:
    """The median pixel value of the ROI."""
    masked_img = self.circle_mask()
    return float(np.nanmedian(masked_img))
```

Am I correct in that this is an error in the documentation?

**Comment by jrkerns** [comment]
Yes, will update. Thanks
