### ISSUE TITLE
CTP528 MTF: Results differ by factor two between v.2.5.1.0 v2.2.6

### ISSUE THREAD

**Issue by TammoGitHub** [jrkerns/pylinac#400]
**Describe the bug**
For CTP528 the number of line pairs / mm differ in between versions 2.2.6 and 2.5.1 by a factor of 2. Which one is correct?

**To Reproduce**
1. Evaluate Images in v226
2. Evaluate same Images in v251
3. Scroll down to MTF results
4. See error: x-axis/results differ by factor 2 

**Expected behavior**
Axes should be the same

**Screenshots**
![graph_v226](https://user-images.githubusercontent.com/88087758/127309765-a791faa8-8d61-4a27-8bc3-213313cac8b3.jpg)
![graph_v251](https://user-images.githubusercontent.com/88087758/127309769-863fcdfb-fe77-4462-ba3e-d59d7abc8ad1.png)

**Comment by jrkerns** [comment]
This was changed in v2.2.8 and covered in the changelog: https://pylinac.readthedocs.io/en/latest/changelog.html#id35
