### ISSUE TITLE
save_analyzed_image method for Field Analysis module

### ISSUE THREAD

**Issue by jrenegar** [jrkerns/pylinac#401]
**Is your feature request related to a problem? Please describe.**
The Field Analysis module doesn't seem to have the save_analyzed_image method that is common to other modules like CBCT, or Planar Imaging

**Describe the solution you'd like**
Add this method to Field Analysis, for consistency

**Describe alternatives you've considered**
Can work around by importing matplotlib.pyplot as plt and doing plt.savefig( )

**Comment by jrkerns** [comment]
Good catch. I never use those methods but will add.

**Comment by jrenegar** [comment]
I've found them useful in the QATrack server environment. Thanks!
