### ISSUE TITLE
Can pylinac compare actual vs expected fluence per control point?

### ISSUE THREAD

**Issue by poderj** [jrkerns/pylinac#403]
Hi,

I wanted to check whether pylinac was capable of calculating actual and expected fluence on a control point basis? If not, could this be an added feature in future versions?

Thanks!

**Comment by jrkerns** [comment]
That functionality does not come out of the box; you'd have to do a fair bit of work to get that right now. You are welcome to suggest this on the feature request board: https://pylinac.featureupvote.com/
