### ISSUE TITLE
Add maximum error picket and leaf to results_data

### ISSUE THREAD

**Issue by bearner-hca** [jrkerns/pylinac#404]
In version 3.0, it would be useful if the `max_error_picket` and `max_error_leaf` of the picket fence module were accessible through `results_data`.

Currently I access these values directly from:
```
pf = pylinac.PicketFence(BIN_FILE.path)
pf.analyze(tolerance=tolerance, action_tolerance=action_tolerance)
pf.max_error_picket
pf.max_error_leaf
```

But this is inconsistent with the way other data is accessed in Pylinac.

I would prefer:

```
pf = pylinac.PicketFence(BIN_FILE.path)
pf.analyze(tolerance=tolerance, action_tolerance=action_tolerance)
data = pf.results_data()
data.max_error_picket
data.max_error_leaf
```

**Comment by jrkerns** [comment]
These are now in as of 3.7 https://pylinac.readthedocs.io/en/latest/changelog.html#id5
