### ISSUE TITLE
WinstonLutz   error analysis

### ISSUE THREAD

**Issue by taconi23** [jrkerns/pylinac#407]
Hello. I'm using the  lastest version of Pylinac. The problem is when analized a image from winstonlutz many times the same image.  The cax and BB position in axis X is correct and show same value all times but in axis Y the value change alternatively

the code  to reproduce the behavior is:

from pylinac import WinstonLutz

dir = 'imagenes/31012020'

wl = WinstonLutz(dir)
wl0 = wl.images[0]
wl0.analyze()
print(f'cax_x: {wl0.field_cax.x}, cax_y: {wl0.field_cax.y}')
wl0.analyze()
print(f'cax_x: {wl0.field_cax.x}, cax_y: {wl0.field_cax.y}')
wl0.analyze()
print(f'cax_x: {wl0.field_cax.x}, cax_y: {wl0.field_cax.y}')
wl0.analyze()
print(f'cax_x: {wl0.field_cax.x}, cax_y: {wl0.field_cax.y}')

the results obtained are:

cax_x: 572.3557522123893, cax_y: 571.5522123893805
cax_x: 572.3557522123893, cax_y: 573.4477876106195
cax_x: 572.3557522123893, cax_y: 571.5522123893805
cax_x: 572.3557522123893, cax_y: 573.4477876106195

How we can see  the component in axis Y change.  this is correct?. Thanks

**Comment by jrkerns** [comment]
Closed in v3.6
