### ISSUE TITLE
Catphan slice thickness calculation mismatch with documentation

### ISSUE THREAD

**Issue by keithoffer** [jrkerns/pylinac#416]
In the Catphan documentation, in the calculation procedure for slice thickness [it states](https://pylinac.readthedocs.io/en/stable/cbct_docs.html):

"Based on testing, the FWHM is not always perfectly detected and may not “catch” the profile, giving an undervalued representation. Thus, the two longest profiles are averaged and the value is converted from pixels to mm and multiplied by 0.42."

However in the code it seems to average all four profiles ([line 503 to 505 of pylinac/ct.py](https://github.com/jrkerns/pylinac/blob/dc45dcac184d3b13db045e1f118a07d6c73b6431/pylinac/ct.py#L503)):

```
def meas_slice_thickness(self) -> float:
    """The average slice thickness for the 4 wire measurements in mm."""
    return np.mean(sorted(roi.wire_fwhm*self.mm_per_pixel*0.42 for roi in self.thickness_rois.values()))/(1+2*self.pad)
```

I believe these two should agree. I'm not sure which is more appropriate to change though.

**Comment by jrkerns** [comment]
Good catch. I think this was behavior I initially made but converted later. For backwards compatibility I'll change the docs. Thanks!
