### ISSUE TITLE
Log Analyzer module - Class Dynalog--open file erro

### ISSUE THREAD

**Issue by yang-6256922** [jrkerns/pylinac#418]
It will get an erro when loading a MLC dynalog file witch contain a chinese characters.Beacuase the patient names are chinese characters in the MLC dynalog files.
The statements of 'with open(self.a_logfile) as a_log:' in class of Dynalog in log_analyzer module has no 'encoding=utf-8',that is the reason.I hope to add an 'encoding=' parameter in the Initialization function in class of Dynalog.
This will lead to better compatibility of programs in countries where English is not the mother tongue.

**Comment by jrkerns** [comment]
Good point. Will add it.

**Comment by jrkerns** [comment]
Will be fixed in 3.10 due April 19/20th
