### ISSUE TITLE
Winston Lutz Feature Request

### ISSUE THREAD

**Issue by seandomal** [jrkerns/pylinac#424]
For some Facilities, Winston Lutz is performed with the Varian Isocube were imaging actually reveals a dark bb rather than a light one. The current module cannot locate the bb for this circumstance and I would like to request an update to the thresholding algorithm so I can find the bb. This would be a great addition and very useful in the clinic. Thank you!

Specifically I'm talking about the function: _find_bb in the Winston-Lutz module.

**Comment by jrkerns** [comment]
Good point. I need to add an `invert=True` parameter to the analyze method, which should address this. Would you mind uploading a set of these images I can test. https://forms.gle/kvbwZ4Q9dfvi8BtT6

**Comment by seandomal** [comment]
Just uploaded the files generated for this past monthly QA using the varian isocube, this will be great to be able to address this, thank you!

**Comment by seandomal** [comment]
Any updates on this? @jrkerns

**Comment by jrkerns** [comment]
Closing d/t being stale/no response

**Comment by seandomal** [comment]
@jrkerns I wanted to revisit this issue and provide some additional images. These images don't appear to have any weird artifact but don't seem to be found using the current thresholding in your winston lutz script
[test.zip](https://github.com/jrkerns/pylinac/files/10701642/test.zip)

**Comment by jrkerns** [comment]
Got it, thanks for the dataset. I'll investigate.

**Comment by seandomal** [comment]
@jrkerns have you had a chance to review those images?

**Comment by jrkerns** [comment]
Yes. I tried using a Hough circle detection algorithm as that isn't inversion-specific. However, it didn't pan out as it wasn't precise enough. I think I may have to simply add a parameter to `analyze` to invert the BB detection algorithm.

**Comment by seandomal** [comment]
Wonderful, thank you!

**Comment by jrkerns** [comment]
Now in v3.9
