### ISSUE TITLE
Quartz Modified Phantom for Hypersight machines

### ISSUE THREAD

**Issue by JustinThymePhysics** [jrkerns/pylinac#465]
**Is your feature request related to a problem? Please describe.**
Hypersight Varian feature on Halcyon - has a new HU region for water.

**Describe the solution you'd like**
A new ROI "circle" of water material has been added to the Quartz model for machines with Hypersight option.

**Describe alternatives you've considered**
[2023.08.28.zip](https://github.com/jrkerns/pylinac/files/12665521/2023.08.28.zip)

**Additional context**

**Comment by JustinThymePhysics** [comment]
[SEPT2023Hypersight_HALCBCT_Paterson_py3__Body_CT.pdf](https://github.com/jrkerns/pylinac/files/12665532/SEPT2023Hypersight_HALCBCT_Paterson_py3__Body_CT.pdf)

**Comment by jrkerns** [comment]
Thanks for submitting. I should be able to work with this, although if there's a manual that would be helpful as I can reference it in the documentation.

**Comment by JustinThymePhysics** [comment]
![pg8](https://github.com/jrkerns/pylinac/assets/86430091/8abebe29-80e2-4466-ba61-1462f44272b2)
![pg10](https://github.com/jrkerns/pylinac/assets/86430091/c31c2945-c99a-4c14-87fa-73883d2470bd)
![pg6](https://github.com/jrkerns/pylinac/assets/86430091/f652c75b-7935-44a4-8182-3635a1f709e3)
![pg7](https://github.com/jrkerns/pylinac/assets/86430091/770d6f85-9097-4bcf-bd27-f8a4d1b03a17)
![pg4](https://github.com/jrkerns/pylinac/assets/86430091/84dd63f2-2476-4b86-9cca-853704a16b70)
![pg11](https://github.com/jrkerns/pylinac/assets/86430091/7fb76a5c-2d32-4a17-8777-da8fd6e8a117)

Some relevant pages that discuss the HU topic and phantom revisions attached.
Thanks.
Not sure my email went through but here is my repeated message:
I was able to modify quart source:  I did -45 degrees and double the radius size worked fine and defined a new material called water which set to 0 HU.
But Page 7 says diameter of existing HU samples are 15 mm and the water is 35 mm.

**Comment by jrkerns** [comment]
On its way and will be in the next release.

**Comment by jrkerns** [comment]
https://pylinac.readthedocs.io/en/latest/quart.html#hypersight
