### ISSUE TITLE
Doc badge link in readme broken 

### ISSUE THREAD

**Issue by SimonBiggs** [jrkerns/pylinac#467]
Hi James ☺️

The doc badge link within the readme is broken. Click on the badge for the docs and you get a 404

**Comment by jrkerns** [comment]
Haha, wow that must've been broken a long time. I'll have a fix up soon. Thanks!

**Comment by SimonBiggs** [comment]
My pleasure 🙂. I find these JOSS reviews help find a few little things that tend to hang around the edges. It's quite a nice process. 🙂
