### ISSUE TITLE
Unable to locate Catphan 504

### ISSUE THREAD

**Issue by JianJuly** [jrkerns/pylinac#481]
Hello,

The CatPhan module (504) is unable to handle the following CBCT:
[20240218.zip](https://github.com/jrkerns/pylinac/files/14325566/20240218.zip)

Would you kindly assist me with this?

![image](https://github.com/jrkerns/pylinac/assets/27723341/8d3fc9de-f91d-442e-9140-9a8080716753)

**Comment by jrkerns** [comment]
What version are you using? On the master branch it says the scan extent isn't enough (i.e. not all modules were scanned). 

See here for scan instructions: https://pylinac.readthedocs.io/en/latest/cbct.html#image-acquisition

**Comment by JianJuly** [comment]
> What version are you using? On the master branch it says the scan extent isn't enough (i.e. not all modules were scanned).
> 
> See here for scan instructions: https://pylinac.readthedocs.io/en/latest/cbct.html#image-acquisition

Thank you for. I've upgraded to the latest version 3.17.0, yet encountered the same error as you described. I will proceed to re-scan the module.

> ValueError: The physical scan extent does not match the module configuration. This means not all modules were included in the scan. Rescan the phantom to include allrelevant modules, or remove modules from the analysis.
