### ISSUE TITLE
Dynalog MU Information Not Extracted Correctly

### ISSUE THREAD

**Issue by RS14678** [jrkerns/pylinac#484]
**Describe the bug**
I am trying to use the pylinac library to convert Dynalog log files to DICOM files. However, I have noticed that the extracted MU values from the Dynalog log files always seem to be in the range of 0-25000, and I am unsure if this is indicative of missing MU information or if there's a specific method to retrieve the correct MU information.

![ECD80F73-705B-411a-9ED8-BF09645F73D2](https://github.com/jrkerns/pylinac/assets/27139437/423acf9c-61ec-456f-8b0f-c8e48c1f65b5)

**Comment by jrkerns** [comment]
Per the Dynalog File format specification document (2013):

**Comment by RS14678** [comment]
Thanks James，
Does the statement "all dose fractions range from 0 to 25000" indicate that the MU values retrieved from axis_data.mu.actual are inherently limited or devoid of meaning? Is there a specific calculation method to accurately derive MU information from Dynalog logs? I am eager to receive guidance on extracting the actual MU values. Looking forward to your reply.

**Comment by jrkerns** [comment]
It means the MU are all relative. You'd have to know the MU from, say, the RT plan and then normalize the relative MU to the planned MU.

**Comment by RS14678** [comment]
Thank you so much, according to the method you provided, I have got the data I want.
