### ISSUE TITLE
IC Profiler x-profiles not copying cax dose to correct position

### ISSUE THREAD

**Issue by AnthEspin** [jrkerns/pylinac#485]
**Describe the bug**
Horizontal profiles are incorrectly inserting cax dose in wrong position. 
As Y profiles include 2 extra detectors around the central axis, pylinac is copying the cax dose to +1 and -1.
I believe this should be at +1 and the cax index, so that the the 3 points are next to each other.

**To Reproduce**
Load an IC profiler measurmeent and plot the horizontal plot

**Expected behavior**
It is expected that the responses for 31, 32 and 33 should be the same. 
Response at detectors 30 and 31 should be swapped

**Screenshots**
![image](https://github.com/jrkerns/pylinac/assets/145399743/4d49fbe8-e3e5-4043-8dcf-f22fda4f34b4)

**Additional context**
Line 309 - 311 in core/io.py should be changed from
`            array = np.insert(
                array, center_detector_idx - 1, array[center_detector_idx]
            )`
to 
`            array = np.insert(
                array, center_detector_idx, array[center_detector_idx]
            )`
This should insert the cax dose to the correct position

**Comment by jrkerns** [comment]
Fixed in 3.22.
