### ISSUE TITLE
IBA array detector support request

### ISSUE THREAD

**Issue by lpoupon13** [jrkerns/pylinac#489]
Hi.
This is a feature request, not a problem.
Support of IBA array detector (like Startrack) would be great in the Field Analysis module, in addition to SNC Profiler.
This would allow to calculate metrics required in our QA workflow, based on profiles extracted from IBA opg files.

I've uploaded a sample file to help, by the image donation form.

Congratulations by the way for the hudge work already done by the pylinac authors and contributors !

**Comment by jrkerns** [comment]
Unfortunately, file parsing is outside the scope of pylinac. The existing SNC profiler parser will also be removed in v4.x of pylinac (undefined date as of now). File parsing is done in RadMachine (our commercial platform that uses pylinac which parses many file types including IBA) and while Radformation has been supportive of keeping the image analysis open-source, the file parsing was agreed to fall out of this scope.
