### ISSUE TITLE
Multiple CT series not sorted properly into a Dicom stack

### ISSUE THREAD

**Issue by sarytky** [jrkerns/pylinac#494]
Thank you for the excellent library for physics in radiation therapy! We are currently automating our QA workflow in Oulu, Finland, and Pylinac has been integral in the process.

**Describe the bug**
In case there are images loaded from multiple series with the image.DicomImageStack class, the sorting does not work properly. Since the metadatas variable (see the screenshots below) changes size, self.image_path_keys updates incorrectly.

**To Reproduce**
We encoutered the behavior when exporting multiple series from Eclipse. The import export tool saves all images in the same folder, mixed.

**Expected behavior**
The function should return the sorted paths from the specific UID. This could be solved with some fixes in the code (see the second screenshot below)

**Screenshots**
Code from pylinac 3.22. The metadatas changes size with multiple series, while paths stays the same size.
![pylinac_sorting_bug](https://github.com/jrkerns/pylinac/assets/24296244/4ab54e6b-940a-462a-a18b-b61ea61981b5)

Modifying also the paths variable accordingly, the sorting problem should be avoided.
![pylinac_sorting_bug_corrected](https://github.com/jrkerns/pylinac/assets/24296244/284423c6-2dc0-4478-9680-927fd6455010)

**Comment by jrkerns** [comment]
Ah, thanks for the heads up!

**Comment by jrkerns** [comment]
Will be fixed in 3.26. Many thanks for the suggested code. It worked perfectly.
