### ISSUE TITLE
Suboptimal Image in Log Analyzer Documentation

### ISSUE THREAD

**Issue by tbezo** [jrkerns/pylinac#498]
**Describe the bug**
In the Documentation for the [Log Analyzer](https://pylinac.readthedocs.io/en/latest/log_analyzer.html#plotting-saving-axes-fluences) there is a suboptimal image for the axis_data plot for the gantry difference.

**To Reproduce**
Go to [Log Analyzer Documentation](https://pylinac.readthedocs.io/en/latest/log_analyzer.html#plotting-saving-axes-fluences) and compare images [log_analyzer-3.png](https://pylinac.readthedocs.io/en/latest/_images/log_analyzer-3.png) and [log_analyzer-4.png](https://pylinac.readthedocs.io/en/latest/_images/log_analyzer-4.png). In the second one you can't really see the differences in the gantry position.

**Expected behavior**
better image: ![gantry_diff](https://github.com/jrkerns/pylinac/assets/44639165/f637d691-1fba-4f94-8bf0-14c3b556a276)

**Screenshots**
see above

**Comment by jrkerns** [comment]
Thanks. The plotting is continued from the figure above. Needed a clear figure call. Will be updated shortly. 
![image](https://github.com/user-attachments/assets/72109f26-32c6-4525-855f-374eb99b0b2c)
