### ISSUE TITLE
Not able to run the program 

### ISSUE THREAD

**Issue by Rahul-py-linac** [jrkerns/pylinac#507]
![IMG_20240725_144235](https://github.com/user-attachments/assets/b3897f8a-f208-4fba-ab2b-aa158cc7af4a)
"I have installed LinaQa as per the instructions provided. When I run it in PyCharm, it automatically exits and pops up an error code. While trying to debug, I found that the 'logo.png' file is not available."!

**Comment by jrkerns** [comment]
I think you meant to post on the LinaQA repo? https://github.com/alanphys/LinaQA/issues
