### ISSUE TITLE
Dynalog file analysis failed

### ISSUE THREAD

**Issue by wwdongcoder** [jrkerns/pylinac#511]
**Describe the bug**
When I use dlog = Dynalog(path) with a file name “dynalog.dlg” i got errors "raise ValueError("Unable to decipher log names; ensure dynalogs start with 'A' and 'B'")
ValueError: Unable to decipher log names; ensure dynalogs start with 'A' and 'B'"

**Comment by jrkerns** [comment]
That's not a bug. That's intended behavior. You have to have both the A and B variants. The default format that is dumped by the machine should start with A and B.
