### ISSUE TITLE
TRS398 update

### ISSUE THREAD

**Issue by runphym974** [jrkerns/pylinac#532]
A new version of TRS398 was published in 2024. 
There is a lot of updates, update of Pylinac calibration modules is needed.

**Comment by jrkerns** [comment]
Thanks for the info; I wasn't aware of the update. I haven't updated the module in quite some time and the calculations themselves aren't hard to do. In retrospect I don't think the calibration module adds much to the value of pylinac. So for the time being I won't be updating it. However, I will add a note to the documentation section mentioning the new update. Thanks!
