### ISSUE TITLE
use colormap 'gray' instead of 'Greys' when ploting the images

### ISSUE THREAD

**Issue by chiaitian** [jrkerns/pylinac#70]
Hi, jrkerns
      Thank you for this great work. It has been a lot of help to me.
When i use the cbct module, i find the images are white as the HU lower and dark as the HU higher.
I think because you use colormap 'Greys', and  should use 'gray'?

**Comment by jrkerns** [comment]
Yeah, this is one of those "way back when" mistakes that I never changed because no one said anything (till now =) I'll add it to the list of v1.6 changes. Thanks!
