### ISSUE TITLE
os.startfile only exists in Windows

### ISSUE THREAD

**Issue by bastula** [jrkerns/pylinac#99]
Launching the PDF viewer on platforms other than Windows doesn't work.

Consider using `subprocess.Popen` (or `subprocess.Run` on Python 3.5+)

**Comment by jrkerns** [comment]
Good catch, thanks!

**Comment by bastula** [comment]
Do you want a patch for this? I wasn't sure depending on which way you wanted to proceed (Popen or Run)

**Comment by jrkerns** [comment]
Sure! Probably Popen since py3.4 is still supported.
